---
title: "Covid 19"
author: "Andres Felipe Lagos Ruiz"
date: "8/2/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Differenct countries

The propose of this project it shows the difference case of death, recovery and activate for every country. One example of this is in the country of US and Colombia with the Case of Death

## USA

```{r US, echo = F}
    library(leaflet)
    download.file('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/02-05-2021.csv','data.csv')
    inputs <- read.csv2('data.csv',sep = ',')
    inputs <- inputs[,c('Province_State','Country_Region','Lat','Long_','Deaths','Recovered','Active')]
    country <- inputs[inputs$Country_Region == 'US',]
    names(country) <- c('Province_State','Country_Region','Lat','Lng','Deaths','Recovered','Active')
    country$Lat <- as.numeric(country$Lat)
    country$Lng <- as.numeric(country$Lng)
    country %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight = 2, radius = sqrt(country[,colnames(country) == 'Deaths']) * 100 ,
            popup = country$Province_State, label = country[,colnames(country) == 'Deaths'],
            color = 'Red')
```

## Colombia

```{r COL, echo = F}
    country <- inputs[inputs$Country_Region == 'Colombia',]
    names(country) <- c('Province_State','Country_Region','Lat','Lng','Deaths','Recovered','Active')
    country$Lat <- as.numeric(country$Lat)
    country$Lng <- as.numeric(country$Lng)
    country %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight = 2, radius = sqrt(country[,colnames(country) == 'Deaths']) * 100 ,
            popup = country$Province_State, label = country[,colnames(country) == 'Deaths'],
            color = 'Red')
```

## Active Case in Colombia

```{r active, echo = F}
    country <- inputs[inputs$Country_Region == 'Colombia',]
    names(country) <- c('Province_State','Country_Region','Lat','Lng','Deaths','Recovered','Active')
    country$Lat <- as.numeric(country$Lat)
    country$Lng <- as.numeric(country$Lng)
    country %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight = 2, radius = sqrt(country[,colnames(country) == 'Active']) * 100 ,
            popup = country$Province_State, label = country[,colnames(country) == 'Active'],
            color = 'Yellow')
```

## Recovery case Colombia

```{r recovery, echo = F}
    country <- inputs[inputs$Country_Region == 'Colombia',]
    names(country) <- c('Province_State','Country_Region','Lat','Lng','Deaths','Recovered','Active')
    country$Lat <- as.numeric(country$Lat)
    country$Lng <- as.numeric(country$Lng)
    country %>%
    leaflet() %>%
    addTiles() %>%
    addCircles(weight = 2, radius = sqrt(country[,colnames(country) == 'Recovered']) * 100 ,
            popup = country$Province_State, label = country[,colnames(country) == 'Recovered'],
            color = 'Green')
```